### ISSUE TITLE
handle action/loader errors gracefully

### ISSUE THREAD

**Issue by meatwallace** [meatwallace/vers#22]
- [x] wire up error boundaries everywhere relevant (#64)
- [x] wrapper fn for action/loaders to capture common errors (#64)
- [x] clean up error boundary non-route error case to display error nicely in dev (#67)
- [x] ambiguous error in prod (#67)
